
function(enable_compiler_flag_if_supported flag)
  string(REGEX REPLACE "^[-]+" "" print ${flag})
  string(REPLACE " " "_" print ${print})
  string(REPLACE "," "_" print ${print})
  string(REPLACE "-" "_" print ${print})
  if(CMAKE_C_COMPILER)
    string(FIND "${CMAKE_C_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_c_compiler_flag("${flag}" ${print}_supported)
        if(${print}_supported)
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flag}" PARENT_SCOPE)
        endif()
        unset(${print}_supported CACHE)
    endif()
  endif()
  if(CMAKE_CXX_COMPILER)
    string(FIND "${CMAKE_CXX_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_cxx_compiler_flag("${flag}" ${print}_supported)
        if(${print}_supported)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flag}" PARENT_SCOPE)
        endif()
        unset(${print}_supported CACHE)
    endif()
  endif()
endfunction()
