
function(enable_linker_flag_if_supported flag)
  string(REGEX REPLACE "^[-]+" "" print ${flag})
  string(REPLACE " " "_" print ${print})
  string(REPLACE "," "_" print ${print})
  string(REPLACE "-" "_" print ${print})
  if(CMAKE_C_COMPILER)
    string(FIND "${CMAKE_EXE_LINKER_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_linker_flag(C "${flag}" ${print}_supported)
        if(${print}_supported)
            set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${flag}" PARENT_SCOPE)
        endif()
        unset(${print}_supported CACHE)
    endif()
  endif()
  if(CMAKE_CXX_COMPILER)
    string(FIND "${CMAKE_EXE_LINKER_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_linker_flag(CXX "${flag}" ${print}_supported)
        if(${print}_supported)
            set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${flag}" PARENT_SCOPE)
        endif()
        unset(${print}_supported CACHE)
    endif()
  endif()
endfunction()
